import React, { useState, useEffect } from 'react';

const zonasBase = [
  { nombre: "Centro Histórico", tipo: "pago", precio: "2€/hora aprox.", tiempo: 5 },
  { nombre: "Centro Histórico", tipo: "gratis", precio: "Gratis", tiempo: 14 },
  { nombre: "Muelle Uno", tipo: "pago", precio: "1.5€/hora aprox.", tiempo: 4 },
  { nombre: "Muelle Uno", tipo: "gratis", precio: "Gratis", tiempo: 12 },
  { nombre: "La Malagueta", tipo: "pago", precio: "2.5€/hora aprox.", tiempo: 5 },
  { nombre: "La Malagueta", tipo: "gratis", precio: "Gratis", tiempo: 16 },
  { nombre: "Teatinos", tipo: "pago", precio: "2€/hora aprox.", tiempo: 5 },
  { nombre: "Teatinos", tipo: "gratis", precio: "Gratis", tiempo: 11 },
  { nombre: "Pedregalejo", tipo: "pago", precio: "1.8€/hora aprox.", tiempo: 5 },
  { nombre: "Pedregalejo", tipo: "gratis", precio: "Gratis", tiempo: 17 },
  { nombre: "El Palo", tipo: "pago", precio: "1.8€/hora aprox.", tiempo: 4 },
  { nombre: "El Palo", tipo: "gratis", precio: "Gratis", tiempo: 18 },
  { nombre: "Huelin", tipo: "pago", precio: "1.8€/hora aprox.", tiempo: 4 },
  { nombre: "Huelin", tipo: "gratis", precio: "Gratis", tiempo: 13 },
  { nombre: "Carretera de Cádiz", tipo: "pago", precio: "1.7€/hora aprox.", tiempo: 5 },
  { nombre: "Carretera de Cádiz", tipo: "gratis", precio: "Gratis", tiempo: 12 },
  { nombre: "Málaga Este", tipo: "pago", precio: "2€/hora aprox.", tiempo: 4 },
  { nombre: "Málaga Este", tipo: "gratis", precio: "Gratis", tiempo: 15 },
  { nombre: "Ciudad Jardín", tipo: "pago", precio: "1.5€/hora aprox.", tiempo: 3 },
  { nombre: "Ciudad Jardín", tipo: "gratis", precio: "Gratis", tiempo: 11 },
  { nombre: "Torremolinos", tipo: "pago", precio: "2€/hora aprox.", tiempo: 4 },
  { nombre: "Torremolinos", tipo: "gratis", precio: "Gratis", tiempo: 16 },
  { nombre: "El Limonar", tipo: "pago", precio: "2€/hora aprox.", tiempo: 5 },
  { nombre: "El Limonar", tipo: "gratis", precio: "Gratis", tiempo: 15 },
  { nombre: "Portada Alta", tipo: "pago", precio: "1.5€/hora aprox.", tiempo: 5 },
  { nombre: "Portada Alta", tipo: "gratis", precio: "Gratis", tiempo: 12 },
  { nombre: "La Luz", tipo: "pago", precio: "1.6€/hora aprox.", tiempo: 5 },
  { nombre: "La Luz", tipo: "gratis", precio: "Gratis", tiempo: 13 },
  { nombre: "Bailén-Miraflores", tipo: "pago", precio: "1.4€/hora aprox.", tiempo: 5 },
  { nombre: "Bailén-Miraflores", tipo: "gratis", precio: "Gratis", tiempo: 14 },
  { nombre: "Puerto de la Torre", tipo: "pago", precio: "1.3€/hora aprox.", tiempo: 5 },
  { nombre: "Puerto de la Torre", tipo: "gratis", precio: "Gratis", tiempo: 10 },
  { nombre: "La Trinidad", tipo: "pago", precio: "1.6€/hora aprox.", tiempo: 5 },
  { nombre: "La Trinidad", tipo: "gratis", precio: "Gratis", tiempo: 13 },
  { nombre: "Cerrado de Calderón", tipo: "pago", precio: "2€/hora aprox.", tiempo: 5 },
  { nombre: "Cerrado de Calderón", tipo: "gratis", precio: "Gratis", tiempo: 16 },
  { nombre: "Capuchinos", tipo: "pago", precio: "1.6€/hora aprox.", tiempo: 5 },
  { nombre: "Capuchinos", tipo: "gratis", precio: "Gratis", tiempo: 14 },
  { nombre: "El Perchel", tipo: "pago", precio: "1.8€/hora aprox.", tiempo: 6 },
  { nombre: "El Perchel", tipo: "gratis", precio: "Gratis", tiempo: 13 },
  { nombre: "La Victoria", tipo: "pago", precio: "1.7€/hora aprox.", tiempo: 6 },
  { nombre: "La Victoria", tipo: "gratis", precio: "Gratis", tiempo: 12 },
  { nombre: "El Ejido", tipo: "pago", precio: "1.5€/hora aprox.", tiempo: 5 },
  { nombre: "El Ejido", tipo: "gratis", precio: "Gratis", tiempo: 14 },
  { nombre: "La Goleta", tipo: "pago", precio: "1.6€/hora aprox.", tiempo: 5 },
  { nombre: "La Goleta", tipo: "gratis", precio: "Gratis", tiempo: 15 },
  { nombre: "Segalerva", tipo: "pago", precio: "1.5€/hora aprox.", tiempo: 4 },
  { nombre: "Segalerva", tipo: "gratis", precio: "Gratis", tiempo: 14 },
  { nombre: "Olletas", tipo: "pago", precio: "1.7€/hora aprox.", tiempo: 5 },
  { nombre: "Olletas", tipo: "gratis", precio: "Gratis", tiempo: 13 }
];

// ... resto del código sin cambios
